/**
 * Fuses the farm view's parts into ONE self-contained HTML string.
 *
 * The app iframe on claude.ai runs under a hardcoded CSP that does not reliably
 * honour declared domains, so the resource must have zero external references:
 * no CDN scripts, no web fonts, no remote images. Everything — CSS, JS, sprites,
 * and the map data — is inlined here, and `test/ui/build.test.ts` fails the
 * build if any external URL sneaks back in.
 *
 * Output: src/ui/generated/farm-view.html.ts, exporting the HTML as a string so
 * the Worker can serve it without any filesystem access at runtime.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CROPS } from "../src/data/crops.ts";
import { MAP_ART, MAP_HEIGHT, MAP_WIDTH } from "../src/data/map.ts";

const here = dirname(fileURLToPath(import.meta.url));
const uiDir = join(here, "..", "src", "ui");
const outDir = join(uiDir, "generated");
const outFile = join(outDir, "farm-view.html.ts");

function read(name: string): string {
  return readFileSync(join(uiDir, name), "utf8");
}

/**
 * Map and crop metadata, injected so the view never duplicates game data that
 * already lives in src/data.
 */
function embedPayload(): string {
  const payload = {
    map: {
      width: MAP_WIDTH,
      height: MAP_HEIGHT,
      art: MAP_ART,
    },
    crops: Object.fromEntries(Object.values(CROPS).map((crop) => [crop.id, { name: crop.name }])),
  };
  // </script> inside a JSON literal would close the enclosing script tag.
  return `window.__HOMESTEAD__ = ${JSON.stringify(payload).replace(/</g, "\\u003c")};`;
}

/** Strips the sprite sheet's XML prolog and outer comment, keeping the <svg>. */
function spriteMarkup(): string {
  const raw = read("sprites.svg");
  const start = raw.indexOf("<svg");
  if (start < 0) throw new Error("sprites.svg has no <svg> element");
  return raw.slice(start);
}

export function buildFarmViewHtml(): string {
  const shell = read("index.html");

  const html = shell
    .replace("/*__STYLES__*/", () => read("styles.css"))
    .replace("<!--__SPRITES__-->", () => spriteMarkup())
    .replace("/*__EMBED__*/", () => embedPayload())
    .replace("/*__APP__*/", () => read("app.js"));

  assertSelfContained(html);
  return html;
}

/**
 * Guards the one rule that breaks the app silently in production: any external
 * reference at all. Checked here as well as in the test suite so a bad build
 * cannot be deployed even if tests are skipped.
 */
export function assertSelfContained(html: string): void {
  const offenders: string[] = [];

  const urlPattern = /(?:https?:)?\/\/[a-z0-9.-]+\.[a-z]{2,}/gi;
  for (const match of html.matchAll(urlPattern)) {
    const value = match[0];
    // XML/SVG namespace declarations are identifiers, not fetches.
    if (value.includes("w3.org")) continue;
    offenders.push(value);
  }

  for (const attr of ["src=", "href="]) {
    const pattern = new RegExp(`${attr}["'](https?:)?//`, "gi");
    for (const match of html.matchAll(pattern)) offenders.push(match[0]);
  }

  if (/@import/i.test(html)) offenders.push("@import");

  if (offenders.length > 0) {
    throw new Error(
      `Farm view must be fully self-contained, but found external references: ${[
        ...new Set(offenders),
      ].join(", ")}`,
    );
  }
}

function main(): void {
  const html = buildFarmViewHtml();

  mkdirSync(outDir, { recursive: true });
  const module = `// GENERATED by scripts/build-ui.ts — do not edit by hand.
// Run \`npm run build:ui\` after changing anything in src/ui/.
/* eslint-disable */

export const FARM_VIEW_HTML = ${JSON.stringify(html)};

export const FARM_VIEW_BYTES = ${Buffer.byteLength(html, "utf8")};
`;
  writeFileSync(outFile, module, "utf8");

  const kb = (Buffer.byteLength(html, "utf8") / 1024).toFixed(1);
  process.stdout.write(`build-ui: wrote ${outFile} (${kb} kB, self-contained)\n`);
}

// Only run when invoked directly, so tests can import the builder.
if (process.argv[1] && process.argv[1].endsWith("build-ui.ts")) {
  main();
}
