import { describe, expect, it } from "vitest";
import { MAX_EVENTS } from "../../src/sim/constants.ts";
import { advance, eventsSince, logEvent } from "../../src/sim/index.ts";
import { buildResult } from "../../src/tools/result.ts";
import { makeFarm } from "../sim/helpers.ts";
import { newGame } from "./harness.ts";

/**
 * The `events` array is how Claude narrates time the player did not see, so its
 * contract matters: everything since the last call, nothing from before it, and
 * correct even after the rolling log has been trimmed.
 */
describe("event reporting", () => {
  it("reports what happened during the gap between calls", async () => {
    const game = await newGame();
    await game.call("get_farm_state");

    await game.call("assign_tasks", {
      tasks: [
        { type: "till", target: "plot_1" },
        { type: "till", target: "plot_2" },
      ],
    });

    game.passTime(60);
    const response = await game.call("get_farm_state");

    // Regression: the cursor used to be read after catch-up, which threw away
    // every event generated by the elapsed time.
    expect(response.events.length).toBeGreaterThan(0);
    expect(response.events.join("\n")).toContain("tilled");
  });

  it("does not repeat events across consecutive calls", async () => {
    const game = await newGame();
    await game.call("assign_tasks", { tasks: [{ type: "till", target: "plot_1" }] });

    game.passTime(60);
    const first = await game.call("get_farm_state");
    const second = await game.call("get_farm_state");

    expect(first.events.length).toBeGreaterThan(0);
    expect(second.events).toHaveLength(0);
  });

  it("survives the rolling log being trimmed", () => {
    const farm = makeFarm();
    const cursor = farm.eventsLogged;

    // Overflow the window by a wide margin.
    for (let i = 0; i < MAX_EVENTS * 3; i++) logEvent(farm, "system", `event ${i}`);

    const since = eventsSince(farm, cursor);
    expect(farm.events.length).toBe(MAX_EVENTS);
    // Everything still in the window is newer than the cursor, so all of it counts.
    expect(since).toHaveLength(MAX_EVENTS);
    expect(since[since.length - 1]?.text).toBe(`event ${MAX_EVENTS * 3 - 1}`);
  });

  it("counts every event ever logged", () => {
    const farm = makeFarm();
    const before = farm.eventsLogged;
    logEvent(farm, "system", "one");
    logEvent(farm, "system", "two");
    expect(farm.eventsLogged).toBe(before + 2);
  });

  it("returns nothing when nothing has happened", () => {
    const farm = makeFarm();
    expect(eventsSince(farm, farm.eventsLogged)).toHaveLength(0);
  });

  it("treats events logged before the cursor as old news", async () => {
    const game = await newGame();
    await game.call("get_farm_state");
    await game.poke((state) => {
      for (let i = 0; i < 30; i++) logEvent(state, "system", `noise ${i}`);
    });

    // No game time has passed, so nothing is new since the last call.
    const response = await game.call("get_farm_state");
    expect(response.events).toHaveLength(0);
  });

  it("caps how many events one result narrates", () => {
    const farm = makeFarm();
    for (let i = 0; i < 200; i++) logEvent(farm, "system", `noise ${i}`);

    const result = buildResult(farm, { summary: "test", eventCursor: 0 });
    const payload = result.structuredContent as { events: string[] };
    const text = (result.content as { type: string; text: string }[])[0]?.text ?? "";

    expect(payload.events.length).toBe(25);
    expect(text).toContain("earlier lines omitted");
    // The most recent events are the ones kept.
    expect(payload.events[payload.events.length - 1]).toBe("noise 199");
  });

  it("keeps the rolling log bounded no matter how long the farm runs", () => {
    const farm = makeFarm();
    farm.inventory["tomato"] = 500;
    advance(farm, 3000);
    expect(farm.events.length).toBeLessThanOrEqual(MAX_EVENTS);
  });
});
